insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cookley', 16, 'Electronics', 285, 109, 8545.81, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Regrant', 21, 'Electronics', 130, 126, 1281.72, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Quo Lux', 17, 'Food', 309, 8, 5768.51, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Duobam', 36, 'Food', 515, 141, 8800.38, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fixflex', 27, 'Beauty', 424, 172, 8684.93, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Transcof', 13, 'Clothing', 779, 9, 5356.08, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Konklux', 8, 'Clothing', 950, 148, 2095.65, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cookley', 19, 'Electronics', 407, 200, 8762.12, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Konklux', 30, 'Food', 936, 104, 6782.04, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Keylex', 23, 'Home Goods', 492, 31, 1723.53, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Holdlamis', 34, 'Food', 447, 162, 7956.14, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zaam-Dox', 19, 'Clothing', 407, 108, 7908.19, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Voltsillam', 19, 'Home Goods', 414, 96, 7420.72, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tempsoft', 37, 'Beauty', 843, 101, 1653.08, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 25, 'Clothing', 909, 150, 931.15, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 11, 'Home Goods', 907, 31, 8412.76, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Flowdesk', 32, 'Electronics', 726, 73, 4519.06, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tresom', 27, 'Clothing', 963, 134, 4493.06, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Rank', 48, 'Electronics', 93, 3, 2473.55, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Kanlam', 47, 'Food', 689, 28, 1261.06, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cookley', 25, 'Clothing', 359, 137, 3843.47, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tampflex', 9, 'Electronics', 789, 130, 6488.56, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cookley', 13, 'Beauty', 919, 17, 5462.49, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zoolab', 12, 'Clothing', 980, 161, 4471.0, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 31, 'Home Goods', 314, 191, 6850.81, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Duobam', 1, 'Beauty', 320, 110, 1005.53, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotlux', 27, 'Electronics', 591, 98, 2623.95, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zontrax', 31, 'Home Goods', 870, 142, 2909.84, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zaam-Dox', 49, 'Home Goods', 516, 29, 383.53, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Voltsillam', 39, 'Food', 949, 119, 5753.3, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 5, 'Beauty', 794, 87, 2624.06, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tempsoft', 49, 'Home Goods', 149, 78, 4221.8, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Temp', 26, 'Electronics', 222, 53, 3085.58, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Rank', 10, 'Food', 209, 20, 8302.34, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Subin', 29, 'Beauty', 135, 3, 9680.08, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stim', 37, 'Beauty', 144, 145, 9097.14, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 37, 'Clothing', 307, 12, 8458.17, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stim', 12, 'Home Goods', 829, 198, 9836.39, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Job', 49, 'Home Goods', 96, 119, 3978.77, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 18, 'Beauty', 889, 115, 8937.36, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Duobam', 29, 'Home Goods', 369, 5, 4673.97, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Keylex', 43, 'Food', 855, 193, 2036.91, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Duobam', 49, 'Home Goods', 38, 54, 5407.46, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zoolab', 10, 'Clothing', 666, 136, 4617.44, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Treeflex', 39, 'Electronics', 503, 162, 5803.68, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitchip', 4, 'Beauty', 323, 57, 1887.22, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Latlux', 10, 'Electronics', 706, 177, 3882.53, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Overhold', 19, 'Electronics', 509, 186, 8688.55, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Daltfresh', 40, 'Beauty', 500, 197, 1345.37, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Temp', 36, 'Electronics', 412, 14, 9437.63, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Asoka', 28, 'Food', 631, 172, 6799.94, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cookley', 41, 'Beauty', 72, 102, 2965.81, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Keylex', 10, 'Food', 955, 41, 632.9, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tresom', 40, 'Electronics', 42, 169, 7156.15, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Job', 43, 'Food', 835, 4, 333.6, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Span', 4, 'Electronics', 745, 87, 2054.84, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fixflex', 28, 'Beauty', 407, 190, 1608.47, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('It', 45, 'Food', 563, 115, 1889.55, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitwolf', 6, 'Clothing', 618, 186, 9352.28, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Gembucket', 8, 'Beauty', 673, 97, 6819.31, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stim', 45, 'Electronics', 727, 107, 7140.04, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cardify', 31, 'Clothing', 222, 74, 4049.66, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 5, 'Electronics', 485, 158, 2482.26, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tampflex', 23, 'Beauty', 615, 149, 4905.1, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Asoka', 49, 'Home Goods', 824, 199, 6393.08, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 28, 'Food', 277, 101, 8347.08, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Wrapsafe', 25, 'Electronics', 904, 142, 3262.61, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Transcof', 9, 'Home Goods', 75, 35, 3094.98, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fixflex', 50, 'Home Goods', 444, 185, 6119.51, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 8, 'Beauty', 767, 140, 5046.63, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 41, 'Clothing', 250, 32, 2307.11, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Alpha', 31, 'Food', 197, 128, 5575.93, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Rank', 16, 'Food', 259, 190, 2175.25, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Wrapsafe', 40, 'Food', 414, 65, 6138.15, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Hatity', 35, 'Beauty', 21, 82, 8509.52, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stronghold', 22, 'Beauty', 382, 185, 1767.56, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fix San', 28, 'Home Goods', 864, 140, 1673.9, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 46, 'Beauty', 109, 11, 838.48, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 3, 'Electronics', 934, 65, 2955.21, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 38, 'Food', 733, 172, 9625.77, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 23, 'Clothing', 647, 87, 8272.47, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Temp', 2, 'Home Goods', 906, 154, 630.24, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ronstring', 18, 'Food', 132, 25, 5468.0, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sonair', 29, 'Beauty', 775, 134, 3040.75, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Duobam', 39, 'Home Goods', 991, 38, 1519.52, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Hatity', 42, 'Electronics', 16, 190, 5480.29, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Pannier', 24, 'Electronics', 439, 31, 252.24, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Pannier', 30, 'Clothing', 447, 96, 5938.9, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 5, 'Clothing', 550, 55, 4857.22, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Kanlam', 50, 'Beauty', 595, 138, 1585.24, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotstring', 31, 'Food', 422, 166, 7382.63, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Job', 26, 'Electronics', 712, 5, 2568.29, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zaam-Dox', 27, 'Clothing', 902, 95, 9308.34, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 38, 'Home Goods', 164, 66, 992.27, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Vagram', 29, 'Home Goods', 13, 171, 3211.95, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zoolab', 18, 'Electronics', 505, 99, 7545.27, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ventosanzap', 44, 'Electronics', 503, 146, 488.93, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 14, 'Home Goods', 661, 22, 3788.87, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 45, 'Clothing', 854, 61, 1668.66, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Span', 33, 'Electronics', 290, 105, 3503.74, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fintone', 42, 'Electronics', 554, 73, 1078.49, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sub-Ex', 18, 'Home Goods', 217, 158, 5455.64, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 35, 'Food', 633, 60, 272.27, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Job', 19, 'Food', 820, 151, 6705.72, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Hatity', 44, 'Clothing', 237, 147, 3086.45, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Span', 45, 'Electronics', 860, 128, 7233.98, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Wrapsafe', 33, 'Home Goods', 123, 41, 9310.84, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Trippledex', 2, 'Food', 607, 99, 7340.18, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ronstring', 12, 'Electronics', 940, 183, 3910.97, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Alpha', 4, 'Food', 415, 113, 8684.84, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sub-Ex', 14, 'Home Goods', 285, 100, 890.98, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Konklux', 45, 'Home Goods', 224, 125, 3673.78, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 40, 'Food', 366, 158, 4924.51, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Voyatouch', 4, 'Food', 546, 94, 7491.78, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Flexidy', 47, 'Clothing', 197, 12, 6665.97, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Mat Lam Tam', 2, 'Clothing', 764, 63, 7605.48, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Pannier', 26, 'Food', 689, 11, 2074.35, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Subin', 20, 'Food', 462, 55, 5306.23, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Treeflex', 39, 'Beauty', 673, 0, 4598.75, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 5, 'Food', 457, 197, 6953.51, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Wrapsafe', 18, 'Clothing', 285, 10, 6789.59, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zoolab', 28, 'Electronics', 616, 189, 1372.67, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sonsing', 27, 'Electronics', 104, 197, 6645.56, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Redhold', 50, 'Home Goods', 640, 10, 2934.61, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cardguard', 7, 'Home Goods', 296, 83, 3023.58, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Veribet', 27, 'Food', 132, 95, 4698.57, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Konklab', 22, 'Clothing', 860, 135, 3830.83, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 33, 'Clothing', 231, 130, 7657.42, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ventosanzap', 9, 'Beauty', 862, 18, 2909.93, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 45, 'Food', 315, 66, 7197.33, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Latlux', 3, 'Food', 965, 186, 4059.61, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tres-Zap', 5, 'Food', 750, 36, 8079.93, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bytecard', 20, 'Electronics', 119, 82, 5734.46, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Alphazap', 35, 'Food', 637, 167, 4301.64, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 33, 'Electronics', 963, 200, 2247.82, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Namfix', 46, 'Home Goods', 304, 154, 2785.44, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Transcof', 12, 'Electronics', 56, 63, 8042.78, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitwolf', 8, 'Food', 668, 149, 9654.39, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Trippledex', 29, 'Electronics', 74, 74, 1801.95, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tres-Zap', 13, 'Home Goods', 898, 123, 9506.1, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fixflex', 12, 'Food', 439, 146, 9209.8, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 35, 'Beauty', 387, 7, 7605.91, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotlux', 46, 'Clothing', 269, 28, 2994.63, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 15, 'Electronics', 31, 165, 4451.86, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Asoka', 8, 'Food', 824, 115, 8566.07, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Latlux', 44, 'Clothing', 126, 147, 5342.97, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotstring', 42, 'Food', 335, 73, 2232.57, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 42, 'Food', 973, 29, 6752.6, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 38, 'Home Goods', 126, 131, 3752.72, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tampflex', 10, 'Beauty', 179, 99, 2947.57, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Prodder', 18, 'Food', 708, 62, 3633.05, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fix San', 10, 'Clothing', 907, 77, 3670.25, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Gembucket', 38, 'Clothing', 806, 119, 9832.97, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Y-Solowarm', 45, 'Home Goods', 958, 115, 6134.5, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Andalax', 39, 'Food', 713, 98, 5782.08, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bigtax', 22, 'Home Goods', 242, 197, 5052.58, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 21, 'Food', 665, 105, 6677.54, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Y-find', 30, 'Beauty', 434, 7, 9304.34, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 16, 'Food', 36, 81, 8063.95, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Overhold', 42, 'Electronics', 266, 144, 7145.64, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zaam-Dox', 12, 'Home Goods', 557, 122, 9949.77, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cardguard', 22, 'Clothing', 205, 112, 5903.2, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Temp', 7, 'Electronics', 417, 7, 1821.72, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bigtax', 36, 'Home Goods', 836, 191, 7968.73, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 33, 'Home Goods', 648, 124, 5613.41, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 32, 'Electronics', 567, 164, 212.96, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Holdlamis', 15, 'Home Goods', 171, 0, 4929.82, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sub-Ex', 30, 'Beauty', 941, 146, 7748.39, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Regrant', 19, 'Electronics', 558, 26, 5955.63, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Transcof', 34, 'Clothing', 440, 53, 8680.47, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zathin', 7, 'Home Goods', 989, 191, 7729.1, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Hatity', 28, 'Home Goods', 509, 173, 9408.75, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ventosanzap', 35, 'Home Goods', 601, 5, 1379.91, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Y-Solowarm', 33, 'Electronics', 526, 139, 6304.64, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitchip', 4, 'Clothing', 869, 186, 5952.25, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Trippledex', 1, 'Home Goods', 59, 16, 4565.93, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Quo Lux', 7, 'Clothing', 904, 22, 828.24, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 27, 'Food', 271, 15, 9725.59, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 23, 'Food', 95, 27, 1597.45, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Namfix', 22, 'Clothing', 199, 54, 6241.7, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Otcom', 20, 'Home Goods', 775, 174, 5092.06, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Flowdesk', 23, 'Electronics', 601, 25, 4667.21, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Duobam', 19, 'Beauty', 52, 172, 2385.55, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bigtax', 46, 'Home Goods', 203, 26, 4632.57, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 13, 'Food', 355, 11, 4816.02, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 7, 'Food', 915, 163, 7303.41, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ronstring', 15, 'Electronics', 213, 57, 8816.98, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Mat Lam Tam', 46, 'Electronics', 135, 27, 3685.87, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Solarbreeze', 40, 'Beauty', 639, 155, 2136.22, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Daltfresh', 13, 'Clothing', 12, 131, 7895.25, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Hatity', 41, 'Electronics', 389, 196, 5063.92, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Voyatouch', 33, 'Clothing', 638, 149, 2414.71, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Subin', 12, 'Food', 857, 164, 4307.47, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 21, 'Home Goods', 362, 143, 3500.42, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Andalax', 1, 'Beauty', 410, 176, 8760.04, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sonair', 9, 'Beauty', 957, 101, 8600.62, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitwolf', 34, 'Electronics', 299, 20, 1845.06, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cardify', 9, 'Electronics', 672, 35, 5334.62, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ventosanzap', 20, 'Electronics', 757, 131, 2103.22, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zamit', 47, 'Clothing', 990, 32, 996.01, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zontrax', 24, 'Beauty', 74, 108, 1451.88, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stronghold', 10, 'Home Goods', 969, 129, 4355.7, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fixflex', 6, 'Food', 365, 183, 556.51, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Otcom', 35, 'Beauty', 661, 37, 8088.32, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Opela', 31, 'Electronics', 194, 194, 3447.03, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sonair', 23, 'Food', 253, 33, 5252.07, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bytecard', 14, 'Home Goods', 631, 200, 8634.64, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fintone', 45, 'Clothing', 83, 165, 9761.03, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Home Ing', 11, 'Electronics', 482, 1, 2985.44, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tempsoft', 48, 'Food', 518, 163, 4557.21, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Ronstring', 23, 'Food', 692, 38, 4915.84, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 49, 'Home Goods', 993, 146, 5990.1, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zathin', 28, 'Beauty', 312, 112, 5762.06, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Andalax', 8, 'Clothing', 541, 14, 3943.83, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 33, 'Clothing', 569, 102, 8650.67, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Keylex', 16, 'Electronics', 216, 99, 4789.44, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 8, 'Electronics', 243, 200, 8289.33, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 21, 'Home Goods', 972, 146, 4051.2, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zamit', 10, 'Electronics', 752, 29, 4989.54, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cookley', 12, 'Home Goods', 132, 28, 6504.2, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotstring', 9, 'Electronics', 925, 175, 1432.37, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Solarbreeze', 5, 'Clothing', 314, 82, 6568.89, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('It', 18, 'Electronics', 199, 184, 4209.06, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Regrant', 44, 'Clothing', 439, 138, 7104.57, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fixflex', 43, 'Food', 625, 106, 7487.79, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tresom', 12, 'Electronics', 482, 141, 7284.47, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Wrapsafe', 23, 'Food', 202, 52, 8650.08, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bytecard', 15, 'Home Goods', 371, 22, 919.74, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sonsing', 25, 'Beauty', 413, 91, 4116.46, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 13, 'Beauty', 261, 184, 3825.99, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stronghold', 2, 'Electronics', 608, 83, 3832.02, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotstring', 41, 'Beauty', 48, 11, 4777.22, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zathin', 26, 'Home Goods', 226, 184, 3528.91, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cardify', 2, 'Home Goods', 62, 93, 7615.89, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Vagram', 49, 'Home Goods', 246, 132, 5370.64, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotstring', 2, 'Clothing', 283, 183, 5160.8, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Lotlux', 49, 'Beauty', 536, 99, 5131.46, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Alpha', 4, 'Food', 651, 38, 4008.56, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 36, 'Beauty', 43, 195, 5023.63, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stringtough', 15, 'Home Goods', 376, 149, 9654.24, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Mat Lam Tam', 4, 'Clothing', 39, 32, 5871.4, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitchip', 34, 'Electronics', 840, 114, 6540.2, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Regrant', 40, 'Clothing', 590, 3, 8143.89, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tresom', 38, 'Beauty', 584, 18, 461.71, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Flexidy', 21, 'Beauty', 192, 33, 3381.45, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tresom', 28, 'Clothing', 257, 18, 7802.51, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Job', 28, 'Electronics', 657, 133, 2888.3, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stronghold', 48, 'Electronics', 264, 163, 3599.57, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tampflex', 36, 'Beauty', 917, 146, 5492.83, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Asoka', 44, 'Food', 528, 71, 1583.53, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Rank', 26, 'Electronics', 360, 159, 2247.94, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zaam-Dox', 37, 'Electronics', 363, 194, 8511.29, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 36, 'Electronics', 54, 37, 7752.62, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Treeflex', 13, 'Clothing', 918, 57, 5216.26, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitchip', 10, 'Electronics', 162, 49, 9759.95, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitwolf', 41, 'Food', 509, 27, 9374.86, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stronghold', 30, 'Clothing', 650, 174, 1234.66, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tempsoft', 38, 'Home Goods', 753, 14, 5288.62, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Vagram', 37, 'Electronics', 59, 21, 3886.69, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Span', 47, 'Food', 969, 141, 1199.88, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Biodex', 24, 'Food', 610, 17, 4045.44, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Regrant', 17, 'Beauty', 674, 73, 9676.9, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stim', 24, 'Food', 424, 164, 5815.04, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Quo Lux', 43, 'Electronics', 756, 149, 9548.24, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitwolf', 13, 'Clothing', 446, 27, 1539.34, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitchip', 6, 'Home Goods', 299, 34, 7035.48, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Veribet', 25, 'Food', 57, 67, 4940.22, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Andalax', 29, 'Beauty', 235, 121, 8218.8, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tampflex', 29, 'Beauty', 743, 122, 7037.99, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 36, 'Beauty', 12, 51, 2785.41, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Mat Lam Tam', 15, 'Electronics', 290, 66, 6790.13, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Stim', 50, 'Home Goods', 408, 125, 1363.89, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Viva', 47, 'Beauty', 395, 63, 6429.67, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Cardguard', 30, 'Food', 869, 16, 7367.13, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Regrant', 44, 'Food', 575, 159, 9680.69, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Greenlam', 22, 'Electronics', 1000, 178, 4874.26, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fintone', 20, 'Clothing', 955, 75, 1134.2, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 5, 'Food', 738, 115, 5693.6, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bytecard', 33, 'Home Goods', 844, 66, 5754.73, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zathin', 17, 'Food', 14, 65, 1861.61, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Fintone', 44, 'Clothing', 507, 169, 4363.0, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Aerified', 4, 'Clothing', 748, 4, 4326.66, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Solarbreeze', 17, 'Clothing', 199, 155, 9948.56, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Alphazap', 20, 'Food', 434, 152, 8996.89, 'Warehouse F');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Alphazap', 31, 'Clothing', 894, 198, 5919.63, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Solarbreeze', 7, 'Home Goods', 101, 22, 6223.22, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Y-Solowarm', 15, 'Beauty', 245, 19, 6046.35, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Veribet', 7, 'Clothing', 698, 15, 4097.4, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tres-Zap', 19, 'Clothing', 691, 19, 6183.09, 'Warehouse B');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Tin', 8, 'Clothing', 681, 14, 2428.74, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Matsoft', 27, 'Home Goods', 453, 117, 3472.6, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zamit', 36, 'Clothing', 656, 104, 943.13, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Mat Lam Tam', 39, 'Food', 126, 191, 8615.04, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Zamit', 34, 'Home Goods', 627, 97, 5316.48, 'Warehouse A');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Asoka', 40, 'Food', 747, 2, 2393.03, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Sonair', 18, 'Beauty', 266, 105, 8974.31, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Temp', 1, 'Electronics', 897, 41, 798.74, 'Warehouse D');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Bitchip', 31, 'Beauty', 188, 119, 305.87, 'Warehouse C');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Asoka', 23, 'Electronics', 973, 159, 3138.82, 'Warehouse E');
insert into Products (name, supplier_id, category, stock_quantity, reorder_level, price, stored_location) values ('Toughjoyfax', 44, 'Home Goods', 187, 97, 5006.64, 'Warehouse F');
