insert into Supplier (name, contact_name, phone, address) values ('O''Reilly-Waters', 'Dara Abrahamoff', '158-458-9060', '5 Rusk Crossing');
insert into Supplier (name, contact_name, phone, address) values ('Kerluke, Bayer and Skiles', 'Rabbi Waymont', '297-997-1698', '85 Golf Drive');
insert into Supplier (name, contact_name, phone, address) values ('Ritchie, Hills and Huels', 'Valentin Giraudat', '508-454-2135', '5 Packers Crossing');
insert into Supplier (name, contact_name, phone, address) values ('Zemlak and Sons', 'Joletta Merrington', '278-262-2067', '85 Northwestern Plaza');
insert into Supplier (name, contact_name, phone, address) values ('Hayes and Sons', 'Patrice Vela', '511-115-5704', '808 Haas Parkway');
insert into Supplier (name, contact_name, phone, address) values ('Kozey, O''Conner and Willms', 'Shina Colley', '255-916-6570', '9 Bluejay Place');
insert into Supplier (name, contact_name, phone, address) values ('Kshlerin-Fadel', 'Dolli Izhak', '355-631-6306', '5 Springs Lane');
insert into Supplier (name, contact_name, phone, address) values ('Torp and Sons', 'Adelle Dearan', '498-152-5011', '3464 North Lane');
insert into Supplier (name, contact_name, phone, address) values ('Kovacek Inc', 'Nanete Windous', '313-972-0574', '7 Mosinee Hill');
insert into Supplier (name, contact_name, phone, address) values ('Schamberger, Swaniawski and Swift', 'Viva Mardoll', '181-265-1089', '4941 Northport Point');
insert into Supplier (name, contact_name, phone, address) values ('Wilderman-Marvin', 'Waring Thurgood', '310-515-2146', '7 Ryan Alley');
insert into Supplier (name, contact_name, phone, address) values ('Schroeder, Bruen and Ondricka', 'Britteny Macklin', '663-898-0178', '31812 Continental Junction');
insert into Supplier (name, contact_name, phone, address) values ('Johnston, Quigley and Reichel', 'Haze Dawkins', '908-555-8694', '8484 Bayside Point');
insert into Supplier (name, contact_name, phone, address) values ('Ullrich-Bergnaum', 'Johan Ranklin', '417-555-4899', '11184 Jackson Hill');
insert into Supplier (name, contact_name, phone, address) values ('Schimmel, Beier and Effertz', 'Camala Moulton', '824-394-1279', '7823 Delladonna Hill');
insert into Supplier (name, contact_name, phone, address) values ('White, Jenkins and Torphy', 'Nikolai Nelsen', '742-973-7014', '50458 Marquette Parkway');
insert into Supplier (name, contact_name, phone, address) values ('Trantow-Kozey', 'Cullan Steade', '427-171-6793', '9769 Manitowish Terrace');
insert into Supplier (name, contact_name, phone, address) values ('Flatley-Rowe', 'Edgar Strewther', '785-762-0861', '306 Novick Point');
insert into Supplier (name, contact_name, phone, address) values ('Fahey LLC', 'Leodora Aliberti', '737-264-3977', '0676 Arizona Street');
insert into Supplier (name, contact_name, phone, address) values ('Bogisich-Haag', 'Aldo Terry', '171-120-5190', '9 Lighthouse Bay Pass');
insert into Supplier (name, contact_name, phone, address) values ('Monahan Inc', 'Bobbette Gunthorp', '688-982-8544', '39 Arkansas Point');
insert into Supplier (name, contact_name, phone, address) values ('Balistreri and Sons', 'Isobel Marzello', '562-744-6738', '3 Beilfuss Lane');
insert into Supplier (name, contact_name, phone, address) values ('Wehner and Sons', 'Ula Dwelly', '214-827-4626', '2507 Alpine Plaza');
insert into Supplier (name, contact_name, phone, address) values ('Bechtelar, Beatty and Schroeder', 'Broddie Braysher', '771-776-9295', '76303 Dennis Street');
insert into Supplier (name, contact_name, phone, address) values ('Wilkinson, Kerluke and Bode', 'Myles Haynesford', '623-697-1366', '2025 Loftsgordon Terrace');
insert into Supplier (name, contact_name, phone, address) values ('Kiehn-Marks', 'Gilberta Featherston', '701-792-5541', '49 Heffernan Point');
insert into Supplier (name, contact_name, phone, address) values ('Gottlieb, Balistreri and Grant', 'Dave Lynagh', '226-123-8080', '58885 Rigney Terrace');
insert into Supplier (name, contact_name, phone, address) values ('Jacobson-Goodwin', 'Roi Pre', '719-342-2755', '40765 2nd Point');
insert into Supplier (name, contact_name, phone, address) values ('Kutch, Lynch and Dare', 'Aimee Coppin', '973-424-2451', '65207 Rutledge Street');
insert into Supplier (name, contact_name, phone, address) values ('Langosh, Swaniawski and Sipes', 'Gardie Wagnerin', '239-620-9401', '74 Crescent Oaks Lane');
insert into Supplier (name, contact_name, phone, address) values ('Pouros LLC', 'Sande Cordingly', '221-801-8108', '18 Westend Center');
insert into Supplier (name, contact_name, phone, address) values ('Erdman, Grady and Pagac', 'Karine Wiersma', '873-270-9476', '34 Glacier Hill Court');
insert into Supplier (name, contact_name, phone, address) values ('Turner Group', 'Trista Reams', '575-626-1543', '04306 6th Court');
insert into Supplier (name, contact_name, phone, address) values ('Dicki-Haag', 'Neddie Olenikov', '856-245-3720', '2205 Killdeer Hill');
insert into Supplier (name, contact_name, phone, address) values ('Zulauf-Thompson', 'Abigail Olanda', '417-104-4690', '42 Westridge Way');
insert into Supplier (name, contact_name, phone, address) values ('Dare-Corwin', 'Rhiamon Reichartz', '875-986-0734', '04048 Schiller Crossing');
insert into Supplier (name, contact_name, phone, address) values ('Kling and Sons', 'Del Collibear', '791-947-8254', '4 Huxley Place');
insert into Supplier (name, contact_name, phone, address) values ('Schimmel, Leffler and Little', 'Thibaud Wilacot', '393-650-6540', '05 Summer Ridge Way');
insert into Supplier (name, contact_name, phone, address) values ('Ledner LLC', 'Maude Walas', '936-410-4279', '2570 Cardinal Pass');
insert into Supplier (name, contact_name, phone, address) values ('Deckow-Harris', 'Isadora Mobbs', '549-626-1586', '79872 Oneill Pass');
insert into Supplier (name, contact_name, phone, address) values ('DuBuque Group', 'Tess Goulter', '754-781-6074', '9 Cambridge Road');
insert into Supplier (name, contact_name, phone, address) values ('Yundt LLC', 'Jermayne Snelson', '989-402-5275', '6 Carberry Park');
insert into Supplier (name, contact_name, phone, address) values ('Lueilwitz Group', 'Moselle Andrag', '979-141-9492', '4 Monument Trail');
insert into Supplier (name, contact_name, phone, address) values ('Harvey LLC', 'Clea Clamp', '825-307-3660', '33 Barnett Plaza');
insert into Supplier (name, contact_name, phone, address) values ('Schneider, Paucek and Johns', 'Dory Bedinn', '645-910-7611', '52 Northwestern Circle');
insert into Supplier (name, contact_name, phone, address) values ('Mueller-Schneider', 'Erie Osgarby', '612-987-7976', '05035 Northport Street');
insert into Supplier (name, contact_name, phone, address) values ('Wisoky Group', 'Nadya Tommeo', '870-784-8303', '776 Troy Lane');
insert into Supplier (name, contact_name, phone, address) values ('Schumm and Sons', 'Andros Zolini', '784-699-4563', '103 Bunting Road');
insert into Supplier (name, contact_name, phone, address) values ('Auer-Pouros', 'Nicolle Dwerryhouse', '842-815-9328', '9522 Esch Drive');
insert into Supplier (name, contact_name, phone, address) values ('Hintz Group', 'Sky Argabrite', '249-169-7826', '8 Pennsylvania Parkway');
